### ISSUE TITLE
Extraer del material de Scrum los siguientes conceptos: Ceremonias, Artefactos y Roles.

### ISSUE THREAD

**Issue by ailenamodio** [ailenamodio/grupo2_aula5#1]

**Comment by alejandroaramos** [comment]
### Ceremonias:
Sprint Planning Meeting
Daily Scrum Meeting
Sprint Review Meeting
Sprint Retrospective Meeting

### Scrum Artifacts:
Product Backlog
Sprint Backlog
Increment

### Roles Scrum:
Product Owner
Scrum Master
Development Team
Costumers
User
