### ISSUE TITLE
Crear glosario de 10 palabras clave de Base de Datos

### ISSUE THREAD

**Issue by ailenamodio** [ailenamodio/grupo2_aula5#4]

**Comment by alejandroaramos** [comment]
**### Glosario de 10 palabras clave de Base de Datos:**

**Tabla**: Tipo de modelado de datos donde se guarda una información recogida por un sistema.
**Columna**: Representa un tipo único de información acerca de la entidad (atributo)
**Tupla**: También llamada fila, representa un objeto único de datos implícitamente estructurados en una tabla.
**Clave primaria**: Proporciona un valor único para cada fila de la tabla y nos sirve de identificador de registros de forma que con esta clave podamos saber sin ningún tipo de equivocación el registro al cuál identifica. 
**Clave foranea**: Clave que se usa en una tabla secundaria y que coincide con la clave primaria en una tabla primaria relacionada.
**Integridad referencial**: La regla de la integridad referencial establece que cualquier valor de clave foránea no nulo en una tabla secundaria debe hacer referencia a un valor de clave primaria de su tabla primaria en la base de datos.
**Tipo de Atributos**: Cada atributo tiene un tipo de datos asociado. Los más comunes son: BIGINT, DATE, FLOTANTE, INTEGER, VARCHAR.
**VARCHAR**: Los tipos de datos CHAR y VARCHAR almacenan cadenas de hasta n bytes de longitud.
**INTEGER**: El tipo de dato INTEGER permite almacenar números enteros.
**Normalización**: proceso que consiste en designar y aplicar una serie de reglas a las relaciones obtenidas tras el paso del modelo entidad-relación al modelo relacional con objeto de minimizar la redundancia de datos, facilitando su gestión posterior
