### ISSUE TITLE
 Crear una lista en Python denominada “Dueno” 

### ISSUE THREAD

**Issue by ailenamodio** [ailenamodio/grupo2_aula5#9]
Que contenga los siguientes valores, 28957346,  Juan,  Perez, 4789689,  Belgrano 101

Dichos datos se corresponden  con los datos del dueño de un perro (DNI, nombre, apellido, teléfono y dirección). Muestre en pantalla el teléfono del dueño si el DNI es mayor a 26000000.

**Comment by Tarias89** [comment]
Ejercicio 1 Python - Lista Dueno
